deployment:
  tasks:
    - export NODE_ENV=production
    - source /opt/cpanel/ea-nodejs20/enable
    - npm install
    - npm run build # → Gera a pasta .next
    - npm run start # → Usa a .next pra servir o app
