deployment:
  tasks:
    - source /opt/cpanel/ea-nodejs22/enable
    - export NODE_ENV=production
    - echo "📁 Diretório de deploy: $DEPLOYDIR"
    - cd $DEPLOYDIR
    - npm install
    - npm run build
    - npm run export
    - echo "📂 Conteúdo da pasta out:"
    - ls -lah out
    - echo "🚀 Copiando arquivos para public_html"
    - rm -rf ~/public_html/*
    - cp -r out/* ~/public_html/
