export const works = [
  {
    id: '1',
    title: 'Work 1',
    description:
      'This project showcases the renovation of a staircase area. The "before" image depicts a raw, unfinished space under the stairs, while the "after" image reveals a transformed area featuring a finished wall, potentially a closet or storage space, and a decorative tiled floor at the bottom of the stairs.',
    imagens: [
      '/Assets/images/imagens/projectOne/escada-depois.jpg',
      '/Assets/images/imagens/projectOne/escada-antes.jpg',
    ],
    coverImage: '/Assets/images/imagens/projectOne/escada-depois.jpg',
  },
  {
    id: '2',
    title: 'Work 2',
    description:
      'A before-and-after look at a room repaint. The initial photos show the room in preparation, with patched sections on the existing purple walls. The subsequent photos demonstrate the transformation after the application of a new blue paint color to the walls and white paint to the trim, giving the room a completely new aesthetic.',
    imagens: [
      '/Assets/images/imagens/projectTwo/quarto-antes-1.jpg',
      '/Assets/images/imagens/projectTwo/quarto-antes1.1.jpg',
      '/Assets/images/imagens/projectTwo/quarto-antes-1.2.jpg',
      '/Assets/images/imagens/projectTwo/quarto-depois.jpg',
      '/Assets/images/imagens/projectTwo/quarto-depois-1.jpg',
      '/Assets/images/imagens/projectTwo/quarto-depois1.1.jpg',
    ],
    coverImage: '/Assets/images/imagens/projectTwo/quarto-depois1.1.jpg',
  },
  {
    id: '3',
    title: 'Work 3',
    description: 'Description for Work 3',
    imagens: [
      '/Assets/images/imagens/projectTree/antes.jpg',
      '/Assets/images/imagens/projectTree/antes-1.jpg',
      '/Assets/images/imagens/projectTree/antes1.1.jpg',
      '/Assets/images/imagens/projectTree/durante.jpg',
      '/Assets/images/imagens/projectTree/depois.jpg',
      '/Assets/images/imagens/projectTree/depois1.jpg',
      '/Assets/images/imagens/projectTree/depois1.1.jpg',
      '/Assets/images/imagens/projectTree/depois1.2.jpg',
      '/Assets/images/imagens/projectTree/depois1.3.jpg',
      '/Assets/images/imagens/projectTree/depois1.4.jpg',
      '/Assets/images/imagens/projectTree/depois1.5.jpg',
    ],
    coverImage: '/Assets/images/imagens/projectTree/depois.jpg',
  },
  {
    id: '4',
    title: 'Work 4',
    description: 'Description for Work 4',
    imagens: [
      '/Assets/images/imagens/projectFour/antes.jpg',
      '/Assets/images/imagens/projectFour/antes-1.jpg',
      '/Assets/images/imagens/projectFour/antes2.jpg',
      '/Assets/images/imagens/projectFour/depois.jpg',
      '/Assets/images/imagens/projectFour/depois.1.jpg',
      '/Assets/images/imagens/projectFour/depois.2.jpg',
      '/Assets/images/imagens/projectFour/depois.3.jpg',
    ],
    coverImage: '/Assets/images/imagens/projectFour/depois.jpg',
  },
  {
    id: '5',
    title: 'Work 5',
    description: 'Description for Work 5',
    imagens: [
      '/Assets/images/imagens/projectFifit/sotao-antes-2.jpg',
      '/Assets/images/imagens/projectFifit/sotao-antes-3.jpg',
      '/Assets/images/imagens/projectFifit/sotao-durante1.jpg',
      '/Assets/images/imagens/projectFifit/sotao-durante1.1.jpg',
      '/Assets/images/imagens/projectFifit/sotao-durante1.2.jpg',
      '/Assets/images/imagens/projectFifit/sotao-depois1.jpg',
      '/Assets/images/imagens/projectFifit/sotao-depois1.1.jpg',
      '/Assets/images/imagens/projectFifit/sotao-depois1.2.jpg',
    ],
    coverImage: '/Assets/images/imagens/projectFifit/sotao-depois1.2.jpg',
  },
  {
    id: '6',
    title: 'Work 6',
    description: 'Description for Work 6',
    imagens: [
      '/Assets/images/imagens/projectSix/cozinha-before.jpg',
      '/Assets/images/imagens/projectSix/cozinha-before1.jpg',
      '/Assets/images/imagens/projectSix/cozinha-in-progress.jpg',
      '/Assets/images/imagens/projectSix/cozinha-in-progress1.jpg',
      '/Assets/images/imagens/projectSix/cozinha-after.jpg',
      '/Assets/images/imagens/projectSix/cozinha-after1.jpg',
    ],
    coverImage: '/Assets/images/imagens/projectSix/cozinha-before1.jpg',
  },
];
